---
scrutiny_collector_state: present

# Example: "http://localhost:8080"
scrutiny_collector_api_endpoint: "http://192.168.86.174:8091"

# If true, run the collector once during the role execution (in addition to cron).
scrutiny_collector_run_once: true

scrutiny_collector_install_dir: "/opt/scrutiny/bin"
scrutiny_collector_binary_name: "scrutiny-collector-metrics-linux-amd64"

# Uses the GitHub releases "latest" download shortcut.
scrutiny_collector_binary_url: "https://github.com/analogj/scrutiny/releases/latest/download/{{ scrutiny_collector_binary_name }}"
